server {
    listen 80;
    server_name aibuddy.ifi.uzh.ch;
    # Redirect all HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name aibuddy.ifi.uzh.ch;

    ssl_certificate     /etc/letsencrypt/live/aibuddy.ifi.uzh.ch/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aibuddy.ifi.uzh.ch/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        proxy_pass         http://127.0.0.1:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_read_timeout 30;
    }
}
